import type {
  FeeItem,
  GalleryItem,
  NewsArticle,
  PerformanceData,
  SchoolEvent,
} from "../../shared/types/content.js";

export const mockEvents: SchoolEvent[] = [
  {
    id: "1",
    title: "Term 1 Begins",
    date: "2024-01-15T00:00:00Z",
    type: "academic",
    description: "Start of the first term for the new academic year.",
  },
  {
    id: "2",
    title: "Parent-Teacher Meeting",
    date: "2024-02-10T15:00:00Z",
    type: "meeting",
    description: "Quarterly parent-teacher conference to discuss student progress.",
  },
  {
    id: "3",
    title: "Inter-Class Debate Competition",
    date: "2024-02-28T09:00:00Z",
    type: "activity",
    description: "Students showcase speaking and research skills in a debate showdown.",
  },
  {
    id: "4",
    title: "Mid-Term Examinations",
    date: "2024-03-18T00:00:00Z",
    type: "exam",
    description: "First semester examinations covering all core subjects.",
  },
  {
    id: "5",
    title: "Science Fair",
    date: "2024-04-05T09:00:00Z",
    type: "activity",
    description: "Students present science projects to parents and community partners.",
  },
  {
    id: "6",
    title: "Sports Day",
    date: "2024-05-20T07:00:00Z",
    type: "activity",
    description: "Annual athletics and games competition for the whole school.",
  },
  {
    id: "7",
    title: "Career Awareness Week",
    date: "2024-06-12T08:30:00Z",
    type: "academic",
    description: "Guest speakers and workshops helping pupils explore future careers.",
  },
  {
    id: "8",
    title: "Cultural Heritage Festival",
    date: "2024-07-02T10:00:00Z",
    type: "activity",
    description: "Celebration of Tanzanian culture with performances and exhibitions.",
  },
  {
    id: "9",
    title: "Mock National Examinations",
    date: "2024-08-19T00:00:00Z",
    type: "exam",
    description: "Preparation assessments ahead of national examinations.",
  },
  {
    id: "10",
    title: "Community Service Day",
    date: "2024-09-14T07:30:00Z",
    type: "activity",
    description: "Students engage in service projects across the Tanga community.",
  },
  {
    id: "11",
    title: "Parent Literacy Workshop",
    date: "2024-10-05T09:00:00Z",
    type: "meeting",
    description: "Workshop equipping parents with strategies to support reading at home.",
  },
  {
    id: "12",
    title: "Final Examinations",
    date: "2024-11-18T00:00:00Z",
    type: "exam",
    description: "Comprehensive end-of-year examinations for all classes.",
  },
  {
    id: "13",
    title: "Graduation & Awards Ceremony",
    date: "2024-12-06T14:00:00Z",
    type: "activity",
    description: "Celebrating graduating pupils and outstanding achievements.",
  },
];

export const mockNews: NewsArticle[] = [
  {
    id: "1",
    title: "Amani School Achieves 95% Pass Rate in National Exams",
    excerpt: "Our students demonstrate exceptional performance in this year's national examinations.",
    content:
      "We are proud to announce that Amani English Medium Pre and Primary School has achieved a 95% pass rate in this year's national examinations. This outstanding result reflects the dedication of our teachers and the hard work of our students. The success spans across all grade levels, with particular excellence in Mathematics and Science.",
    date: "2024-01-10T00:00:00Z",
    author: "Principal Dr. Joseph Mwangi",
    category: "achievement",
    imageUrl: "/images/optimized/news-exam-success-1200.jpg",
  },
  {
    id: "2",
    title: "New STEM Laboratory Officially Opened",
    excerpt: "State-of-the-art facilities enhance hands-on learning experiences.",
    content:
      "Our newly renovated STEM laboratory was officially opened this week. Equipped with modern computers, microscopes, and laboratory equipment, the space provides students with opportunities for practical, inquiry-based learning. The facility supports our commitment to 21st-century education.",
    date: "2024-01-05T00:00:00Z",
    author: "Facilities Manager",
    category: "facilities",
    imageUrl: "/images/optimized/news-stem-lab-1200.jpg",
  },
  {
    id: "3",
    title: "Student Leadership Camp Builds Future Leaders",
    excerpt: "Selected students participate in week-long development program.",
    content:
      "Twenty students participated in our annual leadership development camp this January. Through workshops, team-building activities, and mentorship sessions, participants developed critical leadership skills. The program focuses on character development, public speaking, and community service.",
    date: "2023-12-28T00:00:00Z",
    author: "Head of Student Affairs",
    category: "student-life",
    imageUrl: "/images/optimized/news-leadership-camp-1200.jpg",
  },
];

export const mockPerformance: PerformanceData = {
  summary: {
    passRate: 95,
    averageScore: 82,
    graduationRate: 98,
    studentSatisfaction: 96,
  },
  bySubject: [
    { subject: "Mathematics", passRate: 92, averageScore: 85 },
    { subject: "English Language", passRate: 96, averageScore: 84 },
    { subject: "Science", passRate: 94, averageScore: 83 },
    { subject: "Social Studies", passRate: 96, averageScore: 81 },
    { subject: "Physical Education", passRate: 98, averageScore: 88 },
  ],
  achievements: [
    "Top 5 performing school in Tanga region (2023)",
    "Highest pass rate in Science category",
    "Winner of Inter-School Debate Championship 2023",
    "Excellence in Sports (3 regional medals)",
    "Award for Best Facilities in East Africa",
  ],
  yearOverYear: [
    { year: 2021, passRate: 87 },
    { year: 2022, passRate: 91 },
    { year: 2023, passRate: 95 },
  ],
};

export const mockGallery: GalleryItem[] = [
  {
    id: "gallery-01",
    title: "Quiet Reading Corner",
    caption: "Students take time to build strong reading habits together.",
    alt: "Students reading together in a quiet classroom corner.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/students-reading-portrait-768.jpg",
    fullUrl: "/images/optimized/students-reading-portrait-1600.jpg",
    orientation: "portrait",
  },
  {
    id: "gallery-02",
    title: "Focused Guidance",
    caption: "Teachers provide one-on-one support during lessons.",
    alt: "Teacher guiding a learner during a classroom activity.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/teacher-guidance-portrait-768.jpg",
    fullUrl: "/images/optimized/teacher-guidance-portrait-1600.jpg",
    orientation: "portrait",
  },
  {
    id: "gallery-03",
    title: "Community Outreach",
    caption: "Learners participate in outreach activities across the community.",
    alt: "Students participating in a community outreach activity.",
    categories: ["community"],
    thumbnailUrl: "/images/optimized/community-outreach-learning-768.jpg",
    fullUrl: "/images/optimized/community-outreach-learning-1600.jpg",
  },
  {
    id: "gallery-04",
    title: "Student Leadership",
    caption: "Learners lead meetings and mentor peers with confidence.",
    alt: "Student leaders holding a meeting with classmates.",
    categories: ["leadership"],
    thumbnailUrl: "/images/optimized/student-leadership-meeting-768.jpg",
    fullUrl: "/images/optimized/student-leadership-meeting-1600.jpg",
  },
  {
    id: "gallery-05",
    title: "Sports Day",
    caption: "Athletics events celebrate teamwork and school spirit.",
    alt: "Students competing during sports day activities.",
    categories: ["sports"],
    thumbnailUrl: "/images/optimized/sports-day-celebration-768.jpg",
    fullUrl: "/images/optimized/sports-day-celebration-1600.jpg",
  },
  {
    id: "gallery-06",
    title: "Science Lab Experiment",
    caption: "Hands-on experiments encourage inquiry and discovery.",
    alt: "Students conducting a science experiment in the lab.",
    categories: ["science-lab"],
    thumbnailUrl: "/images/optimized/science-lab-experiment-768.jpg",
    fullUrl: "/images/optimized/science-lab-experiment-1600.jpg",
  },
  {
    id: "gallery-07",
    title: "Graduation Ceremony",
    caption: "Families celebrate academic milestones together.",
    alt: "Graduating students and families during the ceremony.",
    categories: ["graduation"],
    thumbnailUrl: "/images/optimized/graduation-ceremony-768.jpg",
    fullUrl: "/images/optimized/graduation-ceremony-1600.jpg",
  },
  {
    id: "gallery-08",
    title: "Leadership Portrait",
    caption: "Student leaders model responsibility and service.",
    alt: "Student leader posing confidently in school uniform.",
    categories: ["leadership"],
    thumbnailUrl: "/images/optimized/student-leader-portrait-768.jpg",
    fullUrl: "/images/optimized/student-leader-portrait-1600.jpg",
    orientation: "portrait",
  },
  {
    id: "gallery-09",
    title: "Parent Engagement",
    caption: "Families partner with teachers to support every learner.",
    alt: "Parents meeting with teachers during a school gathering.",
    categories: ["community"],
    thumbnailUrl: "/images/optimized/parent-engagement-768.jpg",
    fullUrl: "/images/optimized/parent-engagement-1600.jpg",
  },
  {
    id: "gallery-10",
    title: "Classroom Presentations",
    caption: "Students share ideas and practice confident speaking.",
    alt: "Student presenting in front of classmates.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/classroom-presentation-768.jpg",
    fullUrl: "/images/optimized/classroom-presentation-1600.jpg",
  },
  {
    id: "gallery-11",
    title: "Collaborative Learning",
    caption: "Teamwork helps learners build confidence and curiosity.",
    alt: "Students collaborating on class assignments.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/student-collaboration-768.jpg",
    fullUrl: "/images/optimized/student-collaboration-1600.jpg",
  },
  {
    id: "gallery-12",
    title: "Athletics Training",
    caption: "Sports training builds resilience and discipline.",
    alt: "Students training during athletics practice.",
    categories: ["sports"],
    thumbnailUrl: "/images/optimized/athletics-training-768.jpg",
    fullUrl: "/images/optimized/athletics-training-1600.jpg",
  },
  {
    id: "gallery-13",
    title: "Focused Lessons",
    caption: "Learners stay engaged through structured lessons.",
    alt: "Students focused on classroom instruction.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/classroom-focus-768.jpg",
    fullUrl: "/images/optimized/classroom-focus-1600.jpg",
  },
  {
    id: "gallery-14",
    title: "Innovation Lab",
    caption: "Students explore technology and creative problem solving.",
    alt: "Students working in an innovation lab.",
    categories: ["science-lab"],
    thumbnailUrl: "/images/optimized/innovation-lab-768.jpg",
    fullUrl: "/images/optimized/innovation-lab-1600.jpg",
  },
  {
    id: "gallery-15",
    title: "Community Celebration",
    caption: "School celebrations build unity and pride.",
    alt: "School community celebrating together.",
    categories: ["community"],
    thumbnailUrl: "/images/optimized/community-celebration-768.jpg",
    fullUrl: "/images/optimized/community-celebration-1600.jpg",
  },
  {
    id: "gallery-16",
    title: "Leadership Planning",
    caption: "Student leaders organize initiatives for the term.",
    alt: "Student leaders planning upcoming activities.",
    categories: ["leadership"],
    thumbnailUrl: "/images/optimized/leadership-planning-768.jpg",
    fullUrl: "/images/optimized/leadership-planning-1600.jpg",
  },
  {
    id: "gallery-17",
    title: "Playground Activity",
    caption: "Play-based learning supports healthy development.",
    alt: "Students playing together on the school grounds.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/playground-activity-768.jpg",
    fullUrl: "/images/optimized/playground-activity-1600.jpg",
  },
  {
    id: "gallery-18",
    title: "Campus Life",
    caption: "Everyday moments capture the heart of Amani School.",
    alt: "Students moving between classes on campus.",
    categories: ["campus-life"],
    thumbnailUrl: "/images/optimized/campus-life-moments-768.jpg",
    fullUrl: "/images/optimized/campus-life-moments-1600.jpg",
  },
  {
    id: "gallery-19",
    title: "Community Support",
    caption: "Families and staff collaborate to support learners.",
    alt: "Community members supporting school initiatives.",
    categories: ["community"],
    thumbnailUrl: "/images/optimized/community-support-768.jpg",
    fullUrl: "/images/optimized/community-support-1600.jpg",
  },
  {
    id: "gallery-20",
    title: "Graduation Highlights",
    caption: "Proud moments shared with staff and families.",
    alt: "Graduation highlights with students and families.",
    categories: ["graduation"],
    thumbnailUrl: "/images/optimized/graduation-highlights-768.jpg",
    fullUrl: "/images/optimized/graduation-highlights-1600.jpg",
  },
  {
    id: "gallery-21",
    title: "Cultural Showcase",
    caption: "Celebrations highlight the vibrant culture of our school community.",
    alt: "Students and staff celebrating cultural traditions together.",
    categories: ["community", "campus-life"],
    thumbnailUrl: "/images/optimized/campus-culture-moment-768.jpg",
    fullUrl: "/images/optimized/campus-culture-moment-1600.jpg",
  },
];

export const mockFees: FeeItem[] = [
  {
    id: "nursery-baby-class",
    category: "Nursery",
    grade: "Baby Class",
    tuitionFee: 1_200_000,
    administrationFee: 150_000,
    optionalCosts: [
      { label: "Transport", amount: 180_000 },
      { label: "Lunch", amount: 120_000 },
    ],
    totalPerTerm: 1_650_000,
  },
  {
    id: "nursery-middle-class",
    category: "Nursery",
    grade: "Middle Class",
    tuitionFee: 1_350_000,
    administrationFee: 150_000,
    optionalCosts: [
      { label: "Transport", amount: 190_000 },
      { label: "Lunch", amount: 120_000 },
    ],
    totalPerTerm: 1_810_000,
  },
  {
    id: "nursery-pre-unit",
    category: "Nursery",
    grade: "Pre-Unit",
    tuitionFee: 1_480_000,
    administrationFee: 170_000,
    optionalCosts: [
      { label: "Transport", amount: 200_000 },
      { label: "Lunch", amount: 130_000 },
    ],
    totalPerTerm: 1_980_000,
  },
  {
    id: "primary-standard-1",
    category: "Primary",
    grade: "Standard 1",
    tuitionFee: 1_650_000,
    administrationFee: 200_000,
    optionalCosts: [
      { label: "Transport", amount: 220_000 },
      { label: "Lunch", amount: 150_000 },
    ],
    totalPerTerm: 2_220_000,
  },
  {
    id: "primary-standard-2",
    category: "Primary",
    grade: "Standard 2",
    tuitionFee: 1_730_000,
    administrationFee: 200_000,
    optionalCosts: [
      { label: "Transport", amount: 220_000 },
      { label: "Lunch", amount: 150_000 },
    ],
    totalPerTerm: 2_300_000,
  },
  {
    id: "primary-standard-3",
    category: "Primary",
    grade: "Standard 3",
    tuitionFee: 1_820_000,
    administrationFee: 210_000,
    optionalCosts: [
      { label: "Transport", amount: 230_000 },
      { label: "Lunch", amount: 160_000 },
    ],
    totalPerTerm: 2_420_000,
  },
  {
    id: "primary-standard-4",
    category: "Primary",
    grade: "Standard 4",
    tuitionFee: 1_900_000,
    administrationFee: 210_000,
    optionalCosts: [
      { label: "Transport", amount: 240_000 },
      { label: "Lunch", amount: 170_000 },
    ],
    totalPerTerm: 2_520_000,
  },
  {
    id: "secondary-form-1",
    category: "Secondary",
    grade: "Form 1",
    tuitionFee: 2_100_000,
    administrationFee: 230_000,
    optionalCosts: [
      { label: "Transport", amount: 260_000 },
      { label: "Lunch", amount: 180_000 },
    ],
    totalPerTerm: 2_770_000,
  },
  {
    id: "secondary-form-2",
    category: "Secondary",
    grade: "Form 2",
    tuitionFee: 2_230_000,
    administrationFee: 230_000,
    optionalCosts: [
      { label: "Transport", amount: 260_000 },
      { label: "Lunch", amount: 190_000 },
    ],
    totalPerTerm: 2_910_000,
  },
  {
    id: "secondary-form-3",
    category: "Secondary",
    grade: "Form 3",
    tuitionFee: 2_380_000,
    administrationFee: 250_000,
    optionalCosts: [
      { label: "Transport", amount: 280_000 },
      { label: "Lunch", amount: 200_000 },
    ],
    totalPerTerm: 3_110_000,
  },
  {
    id: "secondary-form-4",
    category: "Secondary",
    grade: "Form 4",
    tuitionFee: 2_480_000,
    administrationFee: 250_000,
    optionalCosts: [
      { label: "Transport", amount: 280_000 },
      { label: "Lunch", amount: 210_000 },
    ],
    totalPerTerm: 3_220_000,
  },
];

